baseURL: https://in1screenshot.renergarden.online # todo: change site url.
title: in1screenshot # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.


params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: A visual diary of what I've been watching in my days. # todo: change default subtitle for your website.
  copyright: All rights of image reserved for your producers. I'm just an appreciator of these works through these screenshots. # todo: set your copyright type.
  author:  # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    # todo: change these links.
    - icon: 'fa-solid fa-blog'
      url: 'https://viverfruir.renergarden.online'
      landing: true
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://www.linkedin.com/in/rener-rannieri/'
      landing: true
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:rannieri.rener@gmail.com'
      landing: true
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  home: ":filename/"

menu:
  main:
    - name: home
      url: /home/
      weight: 1
    - name: people
      url: /tags/people/
      weight: 2
    - name: nature
      url: /tags/nature/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: about
      url: /about/
      weight: 5
